---
title: "pXRF analysis"
author: "Uine Kailamäki"
date: "11/27/2020"
output: word_document
fig_width: 12 
fig_height: 10 
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

## Title

set.seed(3)

A random seed is set for reprodicibility

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Necessary libraries
# Code for citating packages: citation("dplyr")
library(dplyr); 
library(GGally); 
library(corrplot); 
library(tidyr); 
library(openxlsx); 
library(cluster); 
library(ggplot2); 
library(ggfortify); 
library(pca3d)

# Read data
n2 <- read.xlsx("data/z2-pXRF.xlsx", sep=";")

# For correlation and PCA "Samples" must be rownames instead of factors
rownames(n2) <- n2$Sample
n2 <- n2 %>% select(-Sample)
glimpse(n2)

## ALL SAMPLES, CONTAINING SOIL

# Visualize correlations
cor(n2) %>% corrplot (type = "lower", tl.cex = 0.7, tl.pos="d", cl.pos="r")
ggpairs(n2)
ggplot(n2)

# Calculate the total within sum of squares to find the optimal number of clusters
k_max <- 8
twcss <- sapply(1:k_max, function(k){kmeans(n2, k)$tot.withinss})
qplot(x = 1:k_max, y = twcss, geom = 'line')

# Clustering in ggpairs
km <-kmeans(n2, centers = 2)
cluster_x <- as.factor(km$cluster)
ggpairs(n2, mapping = aes(col = cluster_x))

# PCA
pca_n2 <- prcomp(n2)
summary(pca_n2)

biplot(pca_n2, choices = 1:2, cex = c(0.5, 0.7), col = c("grey80", "deeppink2"))

# GGfortify-plot for PCA results

autoplot(pam(n2, 2), frame = TRUE, frame.type = 'norm', label = TRUE)
autoplot(pam(n2, 3), frame = TRUE, frame.type = 'norm', label = TRUE)

autoplot(fanny(n2, 2), frame = TRUE, label = TRUE)
autoplot(fanny(n2, 3), frame = TRUE, label = TRUE)



#### ONLY MUDBRICKS


# Subset n3 containing only the mudbricks
rownames(n2)
n3 <- n2[-c(35,46,47,48,49,50,51,52), ]
rownames(n3)

# Calculate the total within sum of squares to find the optimal number of clusters
k_max <- 8
twcss <- sapply(1:k_max, function(k){kmeans(n3, k)$tot.withinss})
qplot(x = 1:k_max, y = twcss, geom = 'line')

# PCA
pca_n3 <- prcomp(n3)
summary(pca_n3)

biplot(pca_n3, choices = 1:2, cex = c(0.5, 0.7), col = c("grey80", "deeppink2"))

# GGfortify-plot for PCA results

autoplot(pam(n3, 2), frame = TRUE, frame.type = 'norm', label = TRUE)
autoplot(pam(n3, 3), frame = TRUE, frame.type = 'norm', label = TRUE)


autoplot(fanny(n3, 2), frame = TRUE, label = TRUE, shape = FALSE)
autoplot(fanny(n3, 3), frame = TRUE, label = TRUE)

#Visualize PC:s

plot(pca_n3, type="lines")

# 3D PCA plots



# HCA

# compute divisive hierarchical clustering
hc4 <- diana(n3)

# Divise coefficient; amount of clustering structure found
hc4$dc
## [1] 0.884993

# plot dendrogram
pltree(hc4, cex = 0.6, hang = -1, main = "Dendrogram of diana")



###### NEW PLOTS WITH CLASS INFO #######

# PCA
pca_01 <- prcomp(n2)
summary(pca_01)

pca_02 <- prcomp(n2[2:8])
summary(pca_02)

pca_03 <- prcomp(n2[9:19])
summary(pca_03)

pca_04 <- prcomp(n2[c(9:12,14:19)])
summary(pca_04)

pca_05 <- prcomp(n2[5:13])
summary(pca_05)

pca_06 <- prcomp(n2[8:19])
summary(pca_06)

pca_07 <- prcomp(n2[7:17])
summary(pca_07)

pca_08 <- prcomp(n2[8:17])
summary(pca_08)

pca_09 <- prcomp(n2[1:11])
summary(pca_09)

pca_10 <- prcomp(n2[12:19])
summary(pca_10)

##

## biplot(prcomp(n1[1:19]), choices = 1:2, cex = c(0.5, 0.7), col = c("grey80", "deeppink2"))
## autoplot(prcomp(n1[1:19]), data=n1, colour='Type', shape = FALSE, label = TRUE,  main = "Full data")

biplot(pca_01, choices = 1:2, cex = c(0.5, 0.7), col = c("grey80", "deeppink2"), main = "PCA All elements")
autoplot(pca_01, data=n2, colour='Area', shape = FALSE, label = TRUE,  main = "PCA All elements")

biplot(pca_03, choices = 1:2, cex = c(0.5, 0.7), col = c("grey80", "deeppink2"), main = "9:19")
autoplot(pca_03, data=n1, colour='Type', shape = FALSE, label = TRUE,  main = "9:19")

biplot(pca_04, choices = 1:2, cex = c(0.5, 0.7), col = c("grey80", "deeppink2"), main = "9:12,14:19")
autoplot(pca_04, data=n1, colour='Type', shape = FALSE, label = TRUE,  main = "9:12,14:19")


```


