---
title: "pXRF analysis"
author: "Uine Kailamäki"
date: "11/27/2020"
output: word_document
fig_width: 12 
fig_height: 10 
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, fig.width=12, fig.height=8)

```

## Title

set.seed(3)

A random seed is set for reprodicibility

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Necessary libraries
# Code for citating packages: citation("dplyr")
library(dplyr); 
library(GGally); 
library(corrplot); 
library(tidyr); 
library(openxlsx); 
library(cluster); 
library(ggplot2); 
library(ggfortify); 
library(pca3d)
library(ggdendro) # dendrograms together with ggplot
library(dendextend) # dendrograms - change parameters
library(ggtern) # ternary plots


# Read data
nn <- read.xlsx("data/AY-z2-pXRF.xlsx", sep=";")
nn <- as.data.frame(nn)

# Drop unuseable elements
nn <- nn %>% select(-Al2O3)
nn <- nn %>% select(-SiO2)
nn <- nn %>% select(-P2O5)
nn <- nn %>% select(-CaO)

# For correlation and PCA "Samples" must be rownames instead of factors
rownames(nn) <- nn$Sample
n1 <- nn %>% select(-Sample)
n2 <- n1 %>% select(-Area)
n2 <- n2 %>% select(-Type)

# Area as factor, cannot be used in PCA (select your columns when using n1)

n1$Area <- factor(n1$Area)
n1$Type <- factor(n1$Type)

glimpse(n1)
rownames(n1)
colnames(n1)

glimpse(n2)
rownames(n2)
colnames(n2)

## ALL DATA

# Visualize correlations
cor(n2) %>% corrplot (type = "lower", tl.cex = 1, tl.pos="d", cl.pos="r")
ggpairs(n2)
ggplot(n2)

# Calculate the total within sum of squares to find the optimal number of clusters
k_max <- 8
twcss <- sapply(1:k_max, function(k){kmeans(n2, k)$tot.withinss})
qplot(x = 1:k_max, y = twcss, geom = 'line')

# Clustering in ggpairs
km <-kmeans(n2, centers = 2)
cluster_x <- as.factor(km$cluster)
ggpairs(n2, mapping = aes(col = cluster_x))

# PCA
pca_n2 <- prcomp(n2)
summary(pca_n2)

biplot(pca_n2, choices = 1:2, cex = c(1, 1.2), col = c("grey80", "deeppink2"))

# GGfortify-plot for PCA results

autoplot(pam(n2, 2), frame = TRUE, frame.type = 'norm', label = TRUE)
autoplot(pam(n2, 3), frame = TRUE, frame.type = 'norm', label = TRUE)

autoplot(fanny(n2, 2), frame = TRUE, label = TRUE)
autoplot(fanny(n2, 3), frame = TRUE, label = TRUE)


# HCA

# compute divisive hierarchical clustering
hc4 <- diana(n2)

# Divise coefficient; amount of clustering structure found
hc4$dc

# plot dendrogram
pltree(hc4, cex = 1, hang = -1, main = "Dendrogram of diana")



###### NEW PLOTS WITH CLASS INFO #######

# PCA (don't choose Area!)
pca_01 <- prcomp(n1[3:9])
summary(pca_01)


##

biplot(pca_01, choices = 1:2, cex = c(1, 1.2), col = c("grey80", "deeppink2"), main = "PCA all Ashdod-Yam samples")
autoplot(pca_01, data=n1, colour='Area', shape = FALSE, label = TRUE,  main = "PCA all Ashdod-Yam samples")



### DROP BYZANTINE ###


# Subset n3 containing only the mudbricks
rownames(n1)
n3 <- n1[-c(47:53), ]
rownames(n3)

# PCA (don't choose Area!)
pca_02 <- prcomp(n3[3:9])
summary(pca_02)


##

biplot(pca_02, choices = 1:2, cex = c(1, 1.2), col = c("grey80", "deeppink2"), main = "PCA Ashdod-Yam MB samples")
autoplot(pca_02, data=n3, colour='Area', shape = FALSE, label = TRUE,  main = "PCA Ashdod-Yam MB samples")

# HCA all

glimpse(n1)
dend <- 
    n1[3:9] %>%                         # data
    dist %>%                            # calculate a distance matrix
    hclust(method = "ward.D2") %>%      # hierarchical clustering 
    as.dendrogram %>%                   # turn the object into a dendrogram
    set("branches_k_color", k=3) %>% 
    set("branches_lwd", 1.2) %>%
    set("labels_col", c("red", "black", "blue"), k=3) %>%    
    set("labels_cex", 1) %>% 
    set("leaves_pch", NA) 
# plot the dend in usual "base" plotting engine:
plot(dend)

# HCA of only MB

dend <- 
    n3[3:9] %>%                         # data
    dist %>%                            # calculate a distance matrix
    hclust(method = "ward.D2") %>%      # hierarchical clustering 
    as.dendrogram %>%                   # turn the object into a dendrogram
    set("branches_k_color", k=3) %>% 
    set("branches_lwd", 1.2) %>%
    set("labels_col", c("red", "black", "blue"), k=3) %>%    
    set("labels_cex", 1) %>% 
    set("leaves_pch", NA) 
# plot the dend in usual "base" plotting engine:
plot(dend)


# TERNARY PLOT for clay, silt and sand

#Building the static ternary plot

ggtern(data=data_x, aes(x=clay, y=silt, z=sand)) +
  geom_point() +
  labs(title="Clay silt sand") +
  theme_rgbw()

```


