---
author: "Uine Kailamäki"
output:
  html_document:
    theme: cosmo
    fig_caption: true
    fig_width: 12
    fig_height: 8 
    
---

We did loss on ignition analysis both in the traditional manual method and with a modern TGA for comparison.

#### Data preparation

```{r}
# Libraries
library(openxlsx); 
library(dplyr); 
library(ggplot2); 
library(ggrepel); # Preventing labels from overlapping
library(reshape2) # Melt-function for reshaping data to long form

loi <- read.xlsx("data/loi_PP.xlsx", sep=";")
tga <- read.xlsx("data/tga_PP.xlsx", sep=";")

# Remove rows containing words 'kekkila' (internal standard)
tga <- filter(tga, !grepl('kekkila', Name))

# TGA character columns to numeric
tga[, c(4:7)] <- sapply(tga[, c(4:7)], as.numeric)

# Sample names as rownames
rownames(loi) <- loi$sample
rownames(tga) <- tga$Name

# Creating new columns for analysis by subtracting crucible mass;
# "dry" (mass after drying), "c550" (mass after 550 C), "c950" (mass after 950 C)
loi$dry <- (loi$dry_weight - loi$crucible)
loi$c550mass <- (loi$after_550_C - loi$crucible)
loi$c950mass <- (loi$after_950_C - loi$crucible)

loi$c550 <- (loi$dry - loi$c550mass)/(loi$dry) * 100
loi$c950 <- (loi$c550mass - loi$c950mass)/(loi$c550mass) * 100

# Same with TGA
tga$c550 <- (tga$Dry - tga$Mass_550)/(tga$Dry) * 100
tga$c950 <- (tga$Mass_550 - tga$Mass_950)/(tga$Mass_550) * 100

# Creating MB only subsets
loi_MB <- subset(loi[9:19, ])

tga_MB <- subset(tga[9:20, ])
tga_MB <- subset(tga_MB[-4, ]) # No duplicates

tga_MB1 <- subset(tga[9:22, ]) # Includes some duplicates

# Transforming data to long form (MB only)
loi_MB_long <- loi_MB[c(8,13:14)] 
loi_MB_long <- melt(loi_MB_long, id = "context") 

tga_MB_long <- tga_MB1[c(8,10:11)] 
tga_MB_long <- melt(tga_MB_long, id = "context") 

# Transforming data to long form (Soil included)
loi_long <- loi[c(8,13:14)]
loi_long <- melt(loi_long, id = "context") 

tga_long <- tga[c(8,10:11)]
tga_long <- melt(tga_long, id = "context") 

# Long form data for stacked barplots
loi_long2 <- melt(loi_MB[c(1,13:14)], value.name = "Temp", id= "sample") 

tga_long2 <- melt(tga_MB[c(1,10:11)], value.name = "Temp", id= "Name") 

```

**LOI dataset**: \

```{r}
loi[c(8:9,13:14)]
```

**TGA dataset**: \

```{r}
tga[c(8:9,10:11)]
```

#### Boxplots

```{r}
# Colored boxplots: Trad LOI, MB only
ggplot(loi_MB_long, aes(x = variable, y = value, color = context)) +  
  geom_boxplot() +
  labs(title="Traditional LOI (MB only)",
        x ="Temperature", y = "LOI")

# Colored boxplots: TGA LOI, MB only
ggplot(tga_MB_long, aes(x = variable, y = value, color = context)) +  
  geom_boxplot() +
  labs(title="Thermogravimeter LOI (MB only)",
        x ="Temperature", y = "LOI")

# Colored boxplots: Trad LOI, soil samples included
ggplot(loi_long, aes(x = variable, y = value, color = context)) +  
  geom_boxplot() +
  labs(title="Traditional LOI (soil included)",
        x ="Temperature", y = "LOI")

# Colored boxplots: TGA LOI, soil samples included
ggplot(tga_long, aes(x = variable, y = value, color = context)) +  
  geom_boxplot() +
  labs(title="Thermogravimeter LOI (soil included)",
        x ="Temperature", y = "LOI")

```

#### Biplots

```{r}
# MB only biplot: Trad LOI
ggplot(loi_MB, 
      aes(c550, c950, label = rownames(loi_MB), color = factor(context))) +
      geom_point(size=2) +
      geom_text_repel(size=3) + 
      labs(title = "Traditional LOI: MB only, organic vs. carbonate content", 
           color = "Context",
           x = "Organic LOI (%)", 
           y = "Carbonate LOI (%)") +
      theme(axis.title = element_text())

# MB only biplot: TGA LOI
ggplot(tga_MB, 
      aes(c550, c950, label = rownames(tga_MB), colour = factor(context))) +
      geom_point(size=2) +
      geom_text_repel(size=3) + 
      labs(title = "TGA LOI: MB only, organic vs. carbonate content", 
           color = "Context",
           x = "Organic LOI (%)", 
           y = "Carbonate LOI (%)") +
      theme(axis.title = element_text())

# Color by context biplot: Trad LOI
ggplot(loi, 
      aes(c550, c950, label = rownames(loi), colour = factor(context))) +
      geom_point(size=2, aes(shape = factor(type))) +
      geom_text_repel(size=3) + 
      labs(title = "Traditional LOI, soil included - color by context", 
           color = "Context",
           x = "Organic LOI (%)", 
           y = "Carbonate LOI (%)") +
      theme(axis.title = element_text())

# Color by type biplot: TGA
p1 <- ggplot(tga, 
      aes(c550, c950, label = rownames(tga), colour = factor(type))) +
      geom_point(size=2, aes(shape = factor(context))) +
      geom_text_repel(size=3) + 
      labs(color = "Type",
           shape = "Context",
           x = "Organic LOI (%)", 
           y = "Carbonate LOI (%)") +
      theme(axis.title = element_text(), legend.position="left") 
p1
p1 <- p1 + theme(legend.position="left")

# Combining plots to the same figure
library(patchwork)
p2 <- ggplot(tga) + geom_boxplot(aes(c550, color = context)) + 
      theme(legend.position="left")
p3 <- ggplot(tga) + geom_boxplot(aes(c950, color = context), show.legend = FALSE) +
      coord_flip()

# Simple arrangement
## p2 /
## (p3 | p1)


# Prettier figure
theme_marginal_x <- theme(axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank())
theme_marginal_y <- theme(axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank())
wrap_plots(
  p2 + coord_cartesian(xlim = c(2, 6)) + theme_marginal_x,   
  plot_spacer(),  
  p1 + coord_cartesian(xlim = c(2, 6), ylim = c(10, 35)), 
  p3 + coord_flip(xlim = c(10, 35)) + theme_marginal_y,  
  nrow = 2,
  widths = c(1, 0.3),
  heights = c(0.4, 1)
)

```

#### Stacked barplots

```{r}
# Trad LOI stacked barplot
ggplot(loi_long2, aes(x = reorder(sample, Temp), y = Temp, fill = variable)) +
  geom_bar(stat = 'identity', position = 'stack') + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    labs(title="Traditional LOI (MB only)", 
         fill="Temperature",
         x = "", 
         y = "LOI (%)")

# TGA LOI stacked barplot
ggplot(tga_long2, aes(x = reorder(Name, Temp), y = Temp, fill = variable)) +
  geom_bar(stat = 'identity', position = 'stack') + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    labs(title="Thermogravimeter LOI (MB only)",
         fill="Temperature",
         x = "", 
         y = "LOI (%)")

```

Checking weight loss lineplots for assessing if temperatures could tell us about different carbonate sources

```{r}
# Read the raw data
spectra <- read.xlsx("data/tga_PP_dynamic.xlsx", sep=";")

# Remove any rows containing words 'ERROR' or 'TEST'
spectra <- filter(spectra, grepl('PP|S', Sample))
spectra <- filter(spectra, !grepl('_2', Sample))

# Draw spectra
ggplot(spectra, aes(x=Temp, y=Loss, color=Sample, group=Sample)) +
    geom_line() +
    ggtitle("TGA weight loss curves") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 20))
 
# Draw spectra
ggplot(spectra, aes(x=Temp, y=DTG, color=Sample, group=Sample)) +
    geom_line() +
    ggtitle("TGA 1st derivative weight loss curves") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 20))

# PP-9
spectra_D <- filter(spectra, grepl('PP-9', Sample))
ggplot(spectra_D, aes(x=Temp)) +
    geom_line(aes(y=Loss, color="red", ylab="Mass loss")) +
    geom_line(aes(y=DTG*100, color="blue")) +
    labs(title="PP-9",
         colour="",
         y="DTG") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 20))

# PP-10
spectra_D <- filter(spectra, grepl('PP-10', Sample))
ggplot(spectra_D, aes(x=Temp)) +
    geom_line(aes(y=Loss, color="red", ylab="Mass loss")) +
    geom_line(aes(y=DTG*100, color="blue")) +
    labs(title="PP-10",
         colour="",
         y="DTG") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 20))

# PP-11
spectra_D <- filter(spectra, grepl('PP-11', Sample))
ggplot(spectra_D, aes(x=Temp)) +
    geom_line(aes(y=Loss, color="red", ylab="Mass loss")) +
    geom_line(aes(y=DTG*100, color="blue")) +
    labs(title="PP-11",
         colour="",
         y="DTG") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 20))

# PP-12
spectra_D <- filter(spectra, grepl('PP-12', Sample))
ggplot(spectra_D, aes(x=Temp)) +
    geom_line(aes(y=Loss, color="red", ylab="Mass loss")) +
    geom_line(aes(y=DTG*100, color="blue")) +
    labs(title="PP-12",
         colour="",
         y="DTG") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 20))

# PP-13
spectra_D <- filter(spectra, grepl('PP-13', Sample))
ggplot(spectra_D, aes(x=Temp)) +
    geom_line(aes(y=Loss, color="red", ylab="Mass loss")) +
    geom_line(aes(y=DTG*100, color="blue")) +
    labs(title="PP-13",
         colour="",
         y="DTG") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 20))

# PP-14
spectra_D <- filter(spectra, grepl('PP-14', Sample))
ggplot(spectra_D, aes(x=Temp)) +
    geom_line(aes(y=Loss, color="red", ylab="Mass loss")) +
    geom_line(aes(y=DTG*100, color="blue")) +
    labs(title="PP-14",
         colour="",
         y="DTG") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 20))

# PP-15
spectra_D <- filter(spectra, grepl('PP-15', Sample))
ggplot(spectra_D, aes(x=Temp)) +
    geom_line(aes(y=Loss, color="red", ylab="Mass loss")) +
    geom_line(aes(y=DTG*100, color="blue")) +
    labs(title="PP-15",
         colour="",
         y="DTG") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 20))

# PP-16
spectra_D <- filter(spectra, grepl('PP-16', Sample))
ggplot(spectra_D, aes(x=Temp)) +
    geom_line(aes(y=Loss, color="red", ylab="Mass loss")) +
    geom_line(aes(y=DTG*100, color="blue")) +
    labs(title="PP-16",
         colour="",
         y="DTG") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 20))

# PP-17
spectra_D <- filter(spectra, grepl('PP-17', Sample))
ggplot(spectra_D, aes(x=Temp)) +
    geom_line(aes(y=Loss, color="red", ylab="Mass loss")) +
    geom_line(aes(y=DTG*100, color="blue")) +
    labs(title="PP-17",
         colour="",
         y="DTG") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 20))

# PP-18
spectra_D <- filter(spectra, grepl('PP-18', Sample))
ggplot(spectra_D, aes(x=Temp)) +
    geom_line(aes(y=Loss, color="red", ylab="Mass loss")) +
    geom_line(aes(y=DTG*100, color="blue")) +
    labs(title="PP-18",
         colour="",
         y="DTG") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 20))

# PP-19
spectra_D <- filter(spectra, grepl('PP-19', Sample))
ggplot(spectra_D, aes(x=Temp)) +
    geom_line(aes(y=Loss, color="red", ylab="Mass loss")) +
    geom_line(aes(y=DTG*100, color="blue")) +
    labs(title="PP-19",
         colour="",
         y="DTG") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
    scale_y_continuous(breaks = scales::pretty_breaks(n = 20))

```

