---
author: "Uine Kailamäki"
output:
  html_document:
    theme: cosmo
    fig_caption: true
    fig_width: 12
    fig_height: 8 
  
---

#### Data preparation

```{r}
# Libraries
library(dplyr); 
library(openxlsx); 
library(ggtern);
library(reshape2)

# Read and filter data
grain <- read.xlsx("data/grain_AYB.xlsx", sep=";")

# Remove automatically created averages in order to include results from multiple runs for the same sample
grain <- grain %>% 
  filter(!grepl('Average', Sample)) %>% 
  filter(!grepl('test', Sample))

# Average data by "Sample", "Context" and "Type" columns from the original dataset
grain <- aggregate(grain, by=list(grain$Sample, grain$Context, grain$Type), FUN=mean)

# Remove the now empty columns for clarity
grain <- grain %>% select(-Sample)
grain <- grain %>% select(-Context)
grain <- grain %>% select(-Type)

# Assign sample names ("Group.1") as row names, and rename the other created columns back to "Type" and "Area" for clarity
rownames(grain) <- grain$Group.1
names(grain)[names(grain) == "Group.1"] <- "Sample"
names(grain)[names(grain) == "Group.2"] <- "Context"
names(grain)[names(grain) == "Group.3"] <- "Type"

# Scaling clay-silt-sand portions to values between 0 and 1
# (Otherwise the differences in low clay percentages are too small to differentiate)
normalize <- function(x, na.rm=TRUE){(x-min(x, na.rm=TRUE))/(max(x, na.rm=TRUE)-min(x, na.rm=TRUE))}

# Apply function "normalize" to clay, silt and sand columns
grain_01 <- as.data.frame(apply(grain[5:7], 2, normalize))

```

#### Ternary plots

```{r}
# Ternary plots
ggtern(data=grain_01, aes(x=Clay, y=Sand, z=Silt, color=grain$Context)) +
  labs(title="Clay silt sand") +
  theme_rgbw() +
  theme_nomask() +
  geom_point(size=0) +
  geom_text(aes(label=rownames(grain_01)), size=3)

ggtern(data=grain_01, aes(x=Clay, y=Sand, z=Silt, color=grain$Type)) +
  labs(title="Clay silt sand") +
  theme_nomask() +
  geom_mask() +
  geom_point(size=2) 


```

#### Line plots

```{r}
# Reshaping data to long form
grain_long <- melt(grain[c(1,14:113)], id = "Sample") 

ggplot(grain_long, aes(x=variable, y=value, color=Sample, group=Sample)) +
    geom_line() +
    ggtitle("Grain size distribution curves")

# Stacked barplot
grain_long2 <- melt(grain[c(1,9:13)], id = "Sample") 

ggplot(grain_long2, aes(x = reorder(Sample, value), y = value, fill = variable)) +
  geom_bar(stat = 'identity', position = 'fill') + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

