---
author: "Uine Kailamäki"
output:
  html_document:
    theme: cosmo
    fig_caption: true
    fig_width: 12
    fig_height: 8 
  
---

We did loss on ignition analysis both in the traditional manual method and with a modern TGA for comparison.

#### Data preparation

```{r}
# Libraries
library(openxlsx); 
library(dplyr); 
library(ggplot2); 
library(ggrepel);
library(tidyr); 
library(reshape2) # Melt-function for reshaping data to long form

loi <- read.xlsx("data/loi_AYB.xlsx", sep=";")
tga <- read.xlsx("data/tga_AYB.xlsx", sep=";")

summary(loi)
summary(tga)

# Remove rows containing words 'kekkila' (internal standard)
tga <- filter(tga, !grepl('kekkila', Name))

# TGA character columns to numeric
tga[, c(4:7)] <- sapply(tga[, c(4:7)], as.numeric)

# Sample names as rownames
rownames(loi) <- loi$sample
rownames(tga) <- tga$Name

# Creating new columns for analysis by subtracting crucible mass;
# "dry" (sample mass after drying)
# "c550" (sample mass after 550 C)
# "c950" (sample mass after 950 C)
loi$dry <- (loi$dry_weight - loi$crucible)
loi$c550mass <- (loi$after_550_C - loi$crucible)
loi$c950mass <- (loi$after_950_C - loi$crucible)

loi$c550 <- (loi$dry - loi$c550mass)/(loi$dry) * 100
loi$c950 <- (loi$c550mass - loi$c950mass)/(loi$c550mass) * 100

# Same with TGA
tga$c550 <- (tga$Dry - tga$Mass_550)/(tga$Dry) * 100
tga$c950 <- (tga$Mass_550 - tga$Mass_950)/(tga$Mass_550) * 100

```

#### Manual LOI results

```{r}
# Colored boxplots in same graph
loi_long <- loi[c(8,13:14)]
loi_long <- melt(loi_long, id = "context") # Reshaping data to long form

ggplot(loi_long, aes(x = context, y = value, color = variable)) +  
  geom_boxplot() +
  labs(title="Traditional LOI by context",
        x ="Context", y = "LOI")

# Color by type      
ggplot(loi, 
      aes(c550, c950)) +
      geom_point(size=2, aes(shape = factor(context), colour = factor(type))) +
      labs(title = "Organic vs. carbonate content") +
      xlab('Organic LOI (%)') +
      ylab('Carbonate LOI (%)') +
      theme(axis.title = element_text())

# Stacked barplot (x = reorder(sample, LOI))
loi_long = gather(loi, key = var, value = value, c550, c950)

ggplot(loi_long, aes(x = reorder(sample, value), y = value, fill = var)) +
  geom_bar(stat = 'identity', position = 'stack') + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


```

#### TGA LOI results

```{r}
# Colored boxplots in same graph
tga_long <- tga[c(8,10:11)]
tga_long <- melt(tga_long, id = "context") # Reshaping data to long form

ggplot(tga_long, aes(x = context, y = value, color = variable)) +  
  geom_boxplot() +
  labs(title="Thermogravimeter LOI by context",
        x ="Context", y = "LOI")

# Color by type biplot   
ggplot(tga, 
      aes(c550, c950, label = rownames(tga), colour = factor(type))) +
      geom_point(size=2) +
      geom_text_repel(size=3) + labs(title = "Organic vs. carbonate content") +
      xlab('Organic LOI (%)') +
      ylab('Carbonate LOI (%)') +
      theme(axis.title = element_text())

# Stacked barplot (x = reorder(sample, LOI))
tga_long = gather(tga, key = var, value = value, c550, c950)

ggplot(tga_long, aes(x = reorder(Name, value), y = value, fill = var)) +
  geom_bar(stat = 'identity', position = 'stack') + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```


