---
title: "Ashdod-Yam mudbrick analysis"
author: "Uine Kailamäki"
output:
  html_document:
    theme: cosmo
    fig_caption: true
    fig_width: 12
    fig_height: 8 
    code_folding: hide
  
---


```{r}
# Libraries
library(dplyr); 
library(ggplot2); 
library(ggrepel);
library(rgl);
library(plot3D);
library(colordistance)

```

Colorimetry

```{r}
color1 <- read.table("data/color_AY.txt", header = TRUE, sep = "\t", dec = ",")
rownames(color1) <- color1$Data.Name
color <- subset(color1[, 3:5])
summary(color)

ggplot(color, 
      aes(a, b, label = rownames(color))) +
      geom_point(size=2) +
      geom_text_repel(size=3) + 
      labs(title = "Color") +
      xlab("a D65") +
      ylab("b D65") 

ggplot(color1,
      aes(X, L, label = rownames(color))) +
      geom_point(size=2) +
      geom_text_repel(size=3) +     
      labs(title = "Luminance") +
      ylab("L* (D65)") +
      xlab("Sample number") 

# Simple 3D plot
plot3d(color$L, color$a, color$b)

# Colorful 3D plot with drop lines
scatter3D(color$L, color$a, color$b, 
          phi = 0, bty = "g",  type = "h", 
          ticktype = "detailed", pch = 19, cex = 0.5)
text3D(color$L, color$a, color$b,  labels = rownames(color),
        add = TRUE, colkey = FALSE, cex = 0.5)

```



